[phases.setup]
nixPkgs = ["nodejs_14"]

[phases.install]
cmds = ["rm -rf node_modules package-lock.json", "npm install --legacy-peer-deps"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "npm run start"
